package vista;

import java.awt.Color;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.Driver;
import org.neo4j.driver.GraphDatabase;
import org.neo4j.driver.Session;

/**
 *
 * @author Samue
 */
public class insertarPanel extends javax.swing.JPanel {

    /**
     * Creates new form insertarPersonaPane
     *
     * @param titulo
     */
    String titulo;

    public insertarPanel(String titulo) {
        initComponents();

        //Asignamos el titulo
        this.titulo = titulo;

        //Titulo del panel
        tituloLabel.setText("Insertar " + titulo);

        //ComboBox
        txtTipoDato.setBackground(Color.WHITE);

        //Scroll
        jScrollPane1.getViewport().setBackground(Color.WHITE);

        //Boton
        bAgregar.setBackground(Color.WHITE);
        conjuntoAtributos.setLayout(new BoxLayout(conjuntoAtributos, BoxLayout.Y_AXIS));
    }

    private String leerValor(int i, String tipo) {
        switch (tipo) {
            case "Cadena":
                return "\"" + ((AtributoPanel) conjuntoAtributos.getComponent(i)).txtValorAtributo.getText() + "\"";
            case "Entero":
                return ((AtributoPanel) conjuntoAtributos.getComponent(i)).txtValorAtributoEntero.getValue().toString();
            case "Arreglo":
                int itemCont = ((AtributoPanel) conjuntoAtributos.getComponent(i)).lista.getItemCount();
                String arreglo = "[";

                for (int j = 0; j < itemCont - 1; j++) {
                    arreglo += "\"" + ((AtributoPanel) conjuntoAtributos.getComponent(i)).lista.getItemAt(j) + "\",";
                }

                arreglo += "\"" + ((AtributoPanel) conjuntoAtributos.getComponent(i)).lista.getItemAt(itemCont - 1) + "\"]";

                return arreglo;
            default:
        }
        return null;

    }

    private void crearNodo(String atributos) {
        String expCypher = "CREATE (n:" + titulo + "{" + atributos + "})";
        try {
            Driver driver;
            driver = GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("neo4j", "s,dycsj01"));
            Session session = driver.session();
            session.run(expCypher).consume();
            driver.close();
            JOptionPane.showMessageDialog(null, "El nodo se insertó correctamente", titulo, JOptionPane.INFORMATION_MESSAGE);
            conjuntoAtributos.removeAll();
            conjuntoAtributos.revalidate();
            conjuntoAtributos.repaint();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo hacer la inserción del nodo", titulo, JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        contenedorOpciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTipoDato = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        conjuntoAtributos = new javax.swing.JPanel();
        bAgregar = new javax.swing.JButton();
        contenedorLabels = new javax.swing.JPanel();
        nombreAtributoLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        tipoDatoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setPreferredSize(new java.awt.Dimension(750, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(102, 102, 102));
        tituloLabel.setText("INSERTAR");
        add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        contenedorOpciones.setBackground(new java.awt.Color(252, 252, 252));
        contenedorOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Atributos");

        txtTipoDato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTipoDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cadena", "Entero", "Arreglo" }));
        txtTipoDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoDatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorOpcionesLayout = new javax.swing.GroupLayout(contenedorOpciones);
        contenedorOpciones.setLayout(contenedorOpcionesLayout);
        contenedorOpcionesLayout.setHorizontalGroup(
            contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 519, Short.MAX_VALUE)
                .addComponent(txtTipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contenedorOpcionesLayout.setVerticalGroup(
            contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(contenedorOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 730, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        conjuntoAtributos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout conjuntoAtributosLayout = new javax.swing.GroupLayout(conjuntoAtributos);
        conjuntoAtributos.setLayout(conjuntoAtributosLayout);
        conjuntoAtributosLayout.setHorizontalGroup(
            conjuntoAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        conjuntoAtributosLayout.setVerticalGroup(
            conjuntoAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(conjuntoAtributos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 730, 460));

        bAgregar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bAgregar.setText("Agregar nodo");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });
        add(bAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        contenedorLabels.setBackground(new java.awt.Color(252, 252, 252));
        contenedorLabels.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombreAtributoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombreAtributoLabel.setForeground(new java.awt.Color(102, 102, 102));
        nombreAtributoLabel.setText("Nombre de atributo");

        valorLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valorLabel.setForeground(new java.awt.Color(102, 102, 102));
        valorLabel.setText("Valor");

        tipoDatoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipoDatoLabel.setForeground(new java.awt.Color(102, 102, 102));
        tipoDatoLabel.setText("Tipo de dato");

        javax.swing.GroupLayout contenedorLabelsLayout = new javax.swing.GroupLayout(contenedorLabels);
        contenedorLabels.setLayout(contenedorLabelsLayout);
        contenedorLabelsLayout.setHorizontalGroup(
            contenedorLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLabelsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreAtributoLabel)
                .addGap(81, 81, 81)
                .addComponent(valorLabel)
                .addGap(173, 173, 173)
                .addComponent(tipoDatoLabel)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        contenedorLabelsLayout.setVerticalGroup(
            contenedorLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLabelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAtributoLabel)
                    .addComponent(valorLabel)
                    .addComponent(tipoDatoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(contenedorLabels, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 730, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoDatoActionPerformed
        // TODO add your handling code here:
        AtributoPanel atributoPanel = new AtributoPanel(620, 50, txtTipoDato.getSelectedItem().toString());
        conjuntoAtributos.add(atributoPanel);

        conjuntoAtributos.revalidate();
        conjuntoAtributos.repaint();

        revalidate();
        repaint();

    }//GEN-LAST:event_txtTipoDatoActionPerformed


    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        
        if (conjuntoAtributos.getComponentCount() == 0) {
            JOptionPane.showMessageDialog(null, "Ingresa al menos un atributo",titulo,JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String query = "";
        int n = conjuntoAtributos.getComponentCount();
        String nombreAtributo = "";
        String tipoDato = "";

        for (int i = 0; i < n; i++) {
            nombreAtributo = ((AtributoPanel) conjuntoAtributos.getComponent(i)).txtNombreAtributo.getText();
            tipoDato = ((AtributoPanel) conjuntoAtributos.getComponent(i)).tipoDato;

            if (i == n - 1) {
                query += nombreAtributo + ":" + leerValor(i, tipoDato);
            } else {
                query += nombreAtributo + ":" + leerValor(i, tipoDato) + ",";
            }
        }

        crearNodo(query);

    }//GEN-LAST:event_bAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JPanel conjuntoAtributos;
    private javax.swing.JPanel contenedorLabels;
    private javax.swing.JPanel contenedorOpciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreAtributoLabel;
    private javax.swing.JLabel tipoDatoLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JComboBox<String> txtTipoDato;
    private javax.swing.JLabel valorLabel;
    // End of variables declaration//GEN-END:variables
}
