package vista;

import java.awt.Color;
import java.util.Vector;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.Driver;
import org.neo4j.driver.GraphDatabase;
import org.neo4j.driver.Result;
import org.neo4j.driver.Session;

/**
 *
 * @author Samue
 */
public class InsertarRelaciones extends javax.swing.JPanel {

    int tipo = 1;
    String lista1[] = {"AMISTAD", "CONOCE", "AMA", "FAMILIAR"};
    String lista2[] = {"POSEE", "RENTA", "REGALA", "VENDE", "ADQUIERE"};

    /**
     * Creates new form insertarPersonaPane
     *
     */

    public InsertarRelaciones() {
        initComponents();

        //Boton
        bAgregar.setBackground(Color.WHITE);

        //JcomboBox
        tipoNodo1.setBackground(Color.WHITE);
        tipoNodo2.setBackground(Color.WHITE);
        tipoRelación.setBackground(Color.WHITE);

        crearLista(lista1);
    }

    private void crearLista(String lista[]) {
        tipoRelación.removeAllItems();

        for (int i = 0; i < lista.length; i++) {
            tipoRelación.addItem(lista[i]);
        }
    }

    private void seleccionaLista() {
        String tipo1 = tipoNodo1.getSelectedItem().toString();
        String tipo2 = tipoNodo2.getSelectedItem().toString();

        //Si los dos objetos son del mismo tipo, hay que determinar cual es el tipo de ambos nodos
        if (tipo1.equals(tipo2)) {
            if (tipo1.equals("Persona")) {
                crearLista(lista1);
                tipo = 1;
            } else {
                //
                tipoRelación.removeAllItems();
            }
            //Si los tipos de nodos son distintos, hay que determinar cual es el primer nodo
        } else {
            if (tipo1.equals("Persona")) {
                crearLista(lista2);
                tipo = 2;
            } else {
                //
                tipoRelación.removeAllItems();
            }
        }
    }
    
    private void insertarRelacion(String query) {
        try {
            Driver driver;
            driver = GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("neo4j", "s,dycsj01"));
            Session session = driver.session();
            session.run(query).consume();
            
            nombreAtributo1.setText("");
            nombreAtributo2.setText("");
            valorAtributo1.setText("");
            valorAtributo2.setText("");
            
            JOptionPane.showMessageDialog(null, "La relación se insertó correctamente", "Relaciones", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo insertar la relación", "Relaciones", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean match(String match) {
        try {
            Driver driver;
            driver = GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("neo4j", "s,dycsj01"));
            Session session = driver.session();
            Result r = session.run(match);

            return r.hasNext();

        } catch (Exception e) {
            
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        contenedorOpciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bAgregar = new javax.swing.JButton();
        contenedorLabels = new javax.swing.JPanel();
        nombreAtributoLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        tipoDatoLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        nombreAtributo1 = new javax.swing.JTextField();
        valorAtributo1 = new javax.swing.JTextField();
        tipoNodo1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        nombreAtributo2 = new javax.swing.JTextField();
        valorAtributo2 = new javax.swing.JTextField();
        tipoNodo2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        tipoRelación = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setPreferredSize(new java.awt.Dimension(750, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(102, 102, 102));
        tituloLabel.setText("INSERTAR RELACIONES");
        add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        contenedorOpciones.setBackground(new java.awt.Color(252, 252, 252));
        contenedorOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Atributos");

        javax.swing.GroupLayout contenedorOpcionesLayout = new javax.swing.GroupLayout(contenedorOpciones);
        contenedorOpciones.setLayout(contenedorOpcionesLayout);
        contenedorOpcionesLayout.setHorizontalGroup(
            contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(656, Short.MAX_VALUE))
        );
        contenedorOpcionesLayout.setVerticalGroup(
            contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(contenedorOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 730, 40));

        bAgregar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bAgregar.setText("Agregar relación");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });
        add(bAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        contenedorLabels.setBackground(new java.awt.Color(252, 252, 252));
        contenedorLabels.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombreAtributoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombreAtributoLabel.setForeground(new java.awt.Color(102, 102, 102));
        nombreAtributoLabel.setText("Nombre de atributo");

        valorLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valorLabel.setForeground(new java.awt.Color(102, 102, 102));
        valorLabel.setText("Valor");

        tipoDatoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipoDatoLabel.setForeground(new java.awt.Color(102, 102, 102));
        tipoDatoLabel.setText("Tipo de nodo");

        javax.swing.GroupLayout contenedorLabelsLayout = new javax.swing.GroupLayout(contenedorLabels);
        contenedorLabels.setLayout(contenedorLabelsLayout);
        contenedorLabelsLayout.setHorizontalGroup(
            contenedorLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLabelsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreAtributoLabel)
                .addGap(81, 81, 81)
                .addComponent(valorLabel)
                .addGap(173, 173, 173)
                .addComponent(tipoDatoLabel)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        contenedorLabelsLayout.setVerticalGroup(
            contenedorLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLabelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAtributoLabel)
                    .addComponent(valorLabel)
                    .addComponent(tipoDatoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(contenedorLabels, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 730, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        nombreAtributo1.setForeground(new java.awt.Color(102, 102, 102));
        nombreAtributo1.setText("Nombre atributo");
        nombreAtributo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreAtributo1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreAtributo1FocusLost(evt);
            }
        });

        valorAtributo1.setForeground(new java.awt.Color(102, 102, 102));
        valorAtributo1.setText("Valor");
        valorAtributo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorAtributo1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorAtributo1FocusLost(evt);
            }
        });

        tipoNodo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona", "Objeto" }));
        tipoNodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoNodo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nombreAtributo1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(valorAtributo1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(tipoNodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAtributo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorAtributo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoNodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        nombreAtributo2.setForeground(new java.awt.Color(102, 102, 102));
        nombreAtributo2.setText("Nombre atributo");
        nombreAtributo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreAtributo2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreAtributo2FocusLost(evt);
            }
        });

        valorAtributo2.setForeground(new java.awt.Color(102, 102, 102));
        valorAtributo2.setText("Valor");
        valorAtributo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorAtributo2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorAtributo2FocusLost(evt);
            }
        });

        tipoNodo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona", "Objeto" }));
        tipoNodo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoNodo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nombreAtributo2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(valorAtributo2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(tipoNodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAtributo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorAtributo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoNodo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tipoRelación, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(555, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(tipoRelación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 730, 460));
    }// </editor-fold>//GEN-END:initComponents


    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        String query = "MATCH (a:"+tipoNodo1.getSelectedItem().toString()+"{"+nombreAtributo1.getText()+": '"+valorAtributo1.getText()+"'}),"
                           + "(b:"+tipoNodo2.getSelectedItem().toString()+"{"+nombreAtributo2.getText()+": '"+valorAtributo2.getText()+"'})";
        
        String tipoR = tipoRelación.getSelectedItem().toString();
        
        if (!match(query+" RETURN a,b")) {
            JOptionPane.showMessageDialog(null, "No se encontraron coincidencias","Relaciones",JOptionPane.ERROR_MESSAGE);
            return;
        }

        switch (tipo) {
            case 1:

                String atributo;

                if (tipoRelación.getSelectedItem().toString().equals("FAMILIAR")) {
                    atributo = JOptionPane.showInputDialog("Ingresa el parentesco: ");
                    query += " CREATE (a)-[:" + tipoR + "{parentesco: '" + atributo + "'}]->(b)";
                } else {
                    atributo = JOptionPane.showInputDialog("Ingresa la fecha de inicio: ");
                    query += " CREATE (a)-[:" + tipoR + "{fecha_inicio: '" + atributo + "'}]->(b)";
                }

                break;
            case 2:
                //SEGUN SWITCH, SIRVE PARA VALIDAR LA PETICIÓN DE ATRIBUTOS DEL TIPO DE 2 DE RELACIÓN (PERSONA, OBJETO)    
                switch (tipoR) {
                    case "REGALA", "VENDE", "ADQUIERE" -> {
                        String fecha = JOptionPane.showInputDialog("Ingresa la fecha: ");
                        query += " CREATE (a)-[:" + tipoR + "{fecha: '" + fecha + "'}]->(b)";
                    }
                    case "POSEE" -> {
                        String fechaPosesion = JOptionPane.showInputDialog("Ingresa la fecha: ");
                        int costo = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el costo: "));
                        query += " CREATE (a)-[:" + tipoR + "{fecha_posesion: '" + fechaPosesion + "', costo: "+costo+"}]->(b)";
                    }
                    default -> {
                        String fechaInicio = JOptionPane.showInputDialog("Ingresa la fehca inicio: ");
                        String fechaFin = JOptionPane.showInputDialog("Ingresa la fehca fin: ");
                        int costo = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el costo: "));
                        query += " CREATE (a)-[:" + tipoR + "{fecha_inicio: '"+fechaInicio+"', fecha_fin: '"+fechaFin+"', costo_renta: "+costo+"}]->(b)";   
                    }
                }///////////////////////////////////////////////////////////////////////////////////////////////////////
                break;
            default:
        }
        insertarRelacion(query);
    }//GEN-LAST:event_bAgregarActionPerformed

    private void tipoNodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoNodo1ActionPerformed
        // TODO add your handling code here:
        seleccionaLista();
    }//GEN-LAST:event_tipoNodo1ActionPerformed

    private void tipoNodo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoNodo2ActionPerformed
        // TODO add your handling code here:
        seleccionaLista();
    }//GEN-LAST:event_tipoNodo2ActionPerformed

    private void nombreAtributo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreAtributo1FocusGained
        // TODO add your handling code here:
        if (nombreAtributo1.getText().equals("Nombre atributo")) {
            nombreAtributo1.setText("");
            nombreAtributo1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nombreAtributo1FocusGained

    private void nombreAtributo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreAtributo1FocusLost
        // TODO add your handling code here:
        if (nombreAtributo1.getText().isEmpty()) {
            nombreAtributo1.setText("Nombre atributo");
            nombreAtributo1.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_nombreAtributo1FocusLost

    private void valorAtributo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorAtributo1FocusGained
        // TODO add your handling code here:
        if (valorAtributo1.getText().equals("Valor")) {
            valorAtributo1.setText("");
            valorAtributo1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_valorAtributo1FocusGained

    private void valorAtributo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorAtributo1FocusLost
        // TODO add your handling code here:
        if (valorAtributo1.getText().isEmpty()) {
            valorAtributo1.setText("Valor");
            valorAtributo1.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_valorAtributo1FocusLost

    private void nombreAtributo2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreAtributo2FocusGained
        // TODO add your handling code here:
        if (nombreAtributo2.getText().equals("Nombre atributo")) {
            nombreAtributo2.setText("");
            nombreAtributo2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nombreAtributo2FocusGained

    private void nombreAtributo2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreAtributo2FocusLost
        // TODO add your handling code here:
        if (nombreAtributo2.getText().isEmpty()) {
            nombreAtributo2.setText("Nombre atributo");
            nombreAtributo2.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_nombreAtributo2FocusLost

    private void valorAtributo2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorAtributo2FocusGained
        // TODO add your handling code here:
        if (valorAtributo2.getText().equals("Valor")) {
            valorAtributo2.setText("");
            valorAtributo2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_valorAtributo2FocusGained

    private void valorAtributo2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorAtributo2FocusLost
        // TODO add your handling code here:
        if (valorAtributo2.getText().isEmpty()) {
            valorAtributo2.setText("Valor");
            valorAtributo2.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_valorAtributo2FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JPanel contenedorLabels;
    private javax.swing.JPanel contenedorOpciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField nombreAtributo1;
    private javax.swing.JTextField nombreAtributo2;
    private javax.swing.JLabel nombreAtributoLabel;
    private javax.swing.JLabel tipoDatoLabel;
    private javax.swing.JComboBox<String> tipoNodo1;
    private javax.swing.JComboBox<String> tipoNodo2;
    private javax.swing.JComboBox<String> tipoRelación;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JTextField valorAtributo1;
    private javax.swing.JTextField valorAtributo2;
    private javax.swing.JLabel valorLabel;
    // End of variables declaration//GEN-END:variables
}
