/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Samue
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);
        titleBar.addMouseListener(mouseAdapter);
        titleBar.addMouseMotionListener(mouseAdapter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bPersona = new javax.swing.JLabel();
        bInsertarP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bInsertarO = new javax.swing.JLabel();
        bConsultarNP = new javax.swing.JLabel();
        bConsultarNO = new javax.swing.JLabel();
        bConsultarRelacionesP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contenedorPanel = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        cerrarPanel = new javax.swing.JPanel();
        bCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        bPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bPersona.setForeground(new java.awt.Color(102, 102, 102));
        bPersona.setText("PERSONA");
        bPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bInsertarP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bInsertarP.setForeground(new java.awt.Color(102, 102, 102));
        bInsertarP.setText("Insertar");
        bInsertarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bInsertarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bInsertarPMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("OBJETO");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bInsertarO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bInsertarO.setForeground(new java.awt.Color(102, 102, 102));
        bInsertarO.setText("Insertar");
        bInsertarO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bInsertarO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bInsertarOMouseClicked(evt);
            }
        });

        bConsultarNP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bConsultarNP.setForeground(new java.awt.Color(102, 102, 102));
        bConsultarNP.setText("Consultar nodo");
        bConsultarNP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bConsultarNP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bConsultarNPMouseClicked(evt);
            }
        });

        bConsultarNO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bConsultarNO.setForeground(new java.awt.Color(102, 102, 102));
        bConsultarNO.setText("Consultar nodo");
        bConsultarNO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bConsultarNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bConsultarNOMouseClicked(evt);
            }
        });

        bConsultarRelacionesP.setForeground(new java.awt.Color(102, 102, 102));
        bConsultarRelacionesP.setText("Consultar relaciones");
        bConsultarRelacionesP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bConsultarRelacionesP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bConsultarRelacionesPMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Insertar Relación");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("RELACIONES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(bPersona))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bInsertarP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bConsultarNP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(17, 17, 17))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(bConsultarRelacionesP))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bInsertarO, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bConsultarNO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bPersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bInsertarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bConsultarNP)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bInsertarO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bConsultarNO)
                .addGap(94, 94, 94)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bConsultarRelacionesP)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 160, 610));

        contenedorPanel.setBackground(new java.awt.Color(255, 255, 255));
        contenedorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        contenedorPanel.setLayout(null);
        getContentPane().add(contenedorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 750, 610));

        titleBar.setBackground(new java.awt.Color(255, 255, 255));
        titleBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        cerrarPanel.setBackground(new java.awt.Color(255, 255, 255));
        cerrarPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bCerrar.setText("X");
        bCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cerrarPanelLayout = new javax.swing.GroupLayout(cerrarPanel);
        cerrarPanel.setLayout(cerrarPanelLayout);
        cerrarPanelLayout.setHorizontalGroup(
            cerrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );
        cerrarPanelLayout.setVerticalGroup(
            cerrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap(876, Short.MAX_VALUE)
                .addComponent(cerrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addComponent(cerrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bCerrarMouseClicked

    private void bCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarMouseEntered
        // TODO add your handling code here:
        cerrarPanel.setBackground(Color.red);
        bCerrar.setForeground(Color.WHITE);
    }//GEN-LAST:event_bCerrarMouseEntered

    private void bCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarMouseExited
        // TODO add your handling code here:
        cerrarPanel.setBackground(Color.WHITE);
        bCerrar.setForeground(Color.BLACK);
    }//GEN-LAST:event_bCerrarMouseExited

    private void bInsertarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInsertarPMouseClicked
        // TODO add your handling code here:
        contenedorPanel.removeAll();

        insertarPanel panel = new insertarPanel("Persona");
        panel.setBounds(0, 0, 750, 610);

        contenedorPanel.add(panel);
        contenedorPanel.revalidate();
        contenedorPanel.repaint();
    }//GEN-LAST:event_bInsertarPMouseClicked

    private void bInsertarOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInsertarOMouseClicked
        // TODO add your handling code here:
        contenedorPanel.removeAll();

        insertarPanel panel = new insertarPanel("Objeto");
        panel.setBounds(0, 0, 750, 610);

        contenedorPanel.add(panel);
        contenedorPanel.revalidate();
        contenedorPanel.repaint();
    }//GEN-LAST:event_bInsertarOMouseClicked

    private void bConsultarNPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConsultarNPMouseClicked
        // TODO add your handling code here:
        contenedorPanel.removeAll();

        consultarPanel panel = new consultarPanel("Persona");
        panel.setBounds(0, 0, 750, 610);

        contenedorPanel.add(panel);
        contenedorPanel.revalidate();
        contenedorPanel.repaint();
    }//GEN-LAST:event_bConsultarNPMouseClicked

    private void bConsultarNOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConsultarNOMouseClicked
        // TODO add your handling code here:
        contenedorPanel.removeAll();

        consultarPanel panel = new consultarPanel("Objeto");
        panel.setBounds(0, 0, 750, 610);

        contenedorPanel.add(panel);
        contenedorPanel.revalidate();
        contenedorPanel.repaint();
    }//GEN-LAST:event_bConsultarNOMouseClicked

    private void bConsultarRelacionesPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConsultarRelacionesPMouseClicked
        // TODO add your handling code here:
        contenedorPanel.removeAll();

        ConsultarRelaciones panel = new ConsultarRelaciones();
        panel.setBounds(0, 0, 750, 610);

        contenedorPanel.add(panel);
        contenedorPanel.revalidate();
        contenedorPanel.repaint();
    }//GEN-LAST:event_bConsultarRelacionesPMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        contenedorPanel.removeAll();

        InsertarRelaciones panel = new InsertarRelaciones();
        panel.setBounds(0, 0, 750, 610);

        contenedorPanel.add(panel);
        contenedorPanel.revalidate();
        contenedorPanel.repaint();
    }//GEN-LAST:event_jLabel2MouseClicked

    MouseAdapter mouseAdapter = new MouseAdapter() {
        private Point initialClick;

        @Override
        public void mousePressed(MouseEvent e) {
            initialClick = e.getPoint();
            getComponent(e).setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
        }

        @Override
        public void mouseDragged(MouseEvent e) {
            // Get location of the window
            JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(titleBar);
            int thisX = parent.getLocation().x;
            int thisY = parent.getLocation().y;

            // Determine how much the mouse moved since the initial click
            int xMoved = e.getX() - initialClick.x;
            int yMoved = e.getY() - initialClick.y;

            // Move window to this position
            int X = thisX + xMoved;
            int Y = thisY + yMoved;
            parent.setLocation(X, Y);
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            getComponent(e).setCursor(Cursor.getDefaultCursor());
        }

        private Component getComponent(MouseEvent e) {
            return (Component) e.getSource();
        }
    };

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bCerrar;
    private javax.swing.JLabel bConsultarNO;
    private javax.swing.JLabel bConsultarNP;
    private javax.swing.JLabel bConsultarRelacionesP;
    private javax.swing.JLabel bInsertarO;
    private javax.swing.JLabel bInsertarP;
    private javax.swing.JLabel bPersona;
    private javax.swing.JPanel cerrarPanel;
    private javax.swing.JPanel contenedorPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
